import { Component, AfterViewInit, Input, ElementRef, inject, Injectable,ViewEncapsulation } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ListBox } from '../app/ListBox.component/listbox.component';
@Component({
  selector: 'periodic-table',
  imports: [CommonModule, FormsModule, ListBox],
  templateUrl: './periodictable.component.html',
  styleUrls: ['./periodictable.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class PeriodicTableComponent {
  periodicTable:any= {
    "description": "English representation of the periodic table of chemical elements",
    "totalElements": 118,
    "lastUpdated": "2024-04",
    "elements": [
      {"atomicNumber": 1, "symbol": "H", "name": "Hydrogen", "atomicMass": 1.008, "group": 1, "period": 1, "category": "Nonmetal"},
      {"atomicNumber": 2, "symbol": "He", "name": "Helium", "atomicMass": 4.003, "group": 18, "period": 1, "category": "Noble Gas"},
      {"atomicNumber": 3, "symbol": "Li", "name": "Lithium", "atomicMass": 6.941, "group": 1, "period": 2, "category": "Alkali Metal"},
      {"atomicNumber": 4, "symbol": "Be", "name": "Beryllium", "atomicMass": 9.012, "group": 2, "period": 2, "category": "Alkaline Earth Metal"},
      {"atomicNumber": 5, "symbol": "B", "name": "Boron", "atomicMass": 10.811, "group": 13, "period": 2, "category": "Metalloid"},
      {"atomicNumber": 6, "symbol": "C", "name": "Carbon", "atomicMass": 12.011, "group": 14, "period": 2, "category": "Nonmetal"},
      {"atomicNumber": 7, "symbol": "N", "name": "Nitrogen", "atomicMass": 14.007, "group": 15, "period": 2, "category": "Nonmetal"},
      {"atomicNumber": 8, "symbol": "O", "name": "Oxygen", "atomicMass": 15.999, "group": 16, "period": 2, "category": "Nonmetal"},
      {"atomicNumber": 9, "symbol": "F", "name": "Fluorine", "atomicMass": 18.998, "group": 17, "period": 2, "category": "Halogen"},
      {"atomicNumber": 10, "symbol": "Ne", "name": "Neon", "atomicMass": 20.180, "group": 18, "period": 2, "category": "Noble Gas"},
      {"atomicNumber": 11, "symbol": "Na", "name": "Sodium", "atomicMass": 22.990, "group": 1, "period": 3, "category": "Alkali Metal"},
      {"atomicNumber": 12, "symbol": "Mg", "name": "Magnesium", "atomicMass": 24.305, "group": 2, "period": 3, "category": "Alkaline Earth Metal"},
      {"atomicNumber": 13, "symbol": "Al", "name": "Aluminum", "atomicMass": 26.982, "group": 13, "period": 3, "category": "Post-transition Metal"},
      {"atomicNumber": 14, "symbol": "Si", "name": "Silicon", "atomicMass": 28.086, "group": 14, "period": 3, "category": "Metalloid"},
      {"atomicNumber": 15, "symbol": "P", "name": "Phosphorus", "atomicMass": 30.974, "group": 15, "period": 3, "category": "Nonmetal"},
      {"atomicNumber": 16, "symbol": "S", "name": "Sulfur", "atomicMass": 32.065, "group": 16, "period": 3, "category": "Nonmetal"},
      {"atomicNumber": 17, "symbol": "Cl", "name": "Chlorine", "atomicMass": 35.453, "group": 17, "period": 3, "category": "Halogen"},
      {"atomicNumber": 18, "symbol": "Ar", "name": "Argon", "atomicMass": 39.948, "group": 18, "period": 3, "category": "Noble Gas"},
      {"atomicNumber": 19, "symbol": "K", "name": "Potassium", "atomicMass": 39.098, "group": 1, "period": 4, "category": "Alkali Metal"},
      {"atomicNumber": 20, "symbol": "Ca", "name": "Calcium", "atomicMass": 40.078, "group": 2, "period": 4, "category": "Alkaline Earth Metal"},
      {"atomicNumber": 21, "symbol": "Sc", "name": "Scandium", "atomicMass": 44.956, "group": 3, "period": 4, "category": "Transition Metal"},
      {"atomicNumber": 22, "symbol": "Ti", "name": "Titanium", "atomicMass": 47.867, "group": 4, "period": 4, "category": "Transition Metal"},
      {"atomicNumber": 23, "symbol": "V", "name": "Vanadium", "atomicMass": 50.942, "group": 5, "period": 4, "category": "Transition Metal"},
      {"atomicNumber": 24, "symbol": "Cr", "name": "Chromium", "atomicMass": 51.996, "group": 6, "period": 4, "category": "Transition Metal"},
      {"atomicNumber": 25, "symbol": "Mn", "name": "Manganese", "atomicMass": 54.938, "group": 7, "period": 4, "category": "Transition Metal"},
      {"atomicNumber": 26, "symbol": "Fe", "name": "Iron", "atomicMass": 55.845, "group": 8, "period": 4, "category": "Transition Metal"},
      {"atomicNumber": 27, "symbol": "Co", "name": "Cobalt", "atomicMass": 58.933, "group": 9, "period": 4, "category": "Transition Metal"},
      {"atomicNumber": 28, "symbol": "Ni", "name": "Nickel", "atomicMass": 58.693, "group": 10, "period": 4, "category": "Transition Metal"},
      {"atomicNumber": 29, "symbol": "Cu", "name": "Copper", "atomicMass": 63.546, "group": 11, "period": 4, "category": "Transition Metal"},
      {"atomicNumber": 30, "symbol": "Zn", "name": "Zinc", "atomicMass": 65.380, "group": 12, "period": 4, "category": "Transition Metal"},
      {"atomicNumber": 31, "symbol": "Ga", "name": "Gallium", "atomicMass": 69.723, "group": 13, "period": 4, "category": "Post-transition Metal"},
      {"atomicNumber": 32, "symbol": "Ge", "name": "Germanium", "atomicMass": 72.640, "group": 14, "period": 4, "category": "Metalloid"},
      {"atomicNumber": 33, "symbol": "As", "name": "Arsenic", "atomicMass": 74.922, "group": 15, "period": 4, "category": "Metalloid"},
      {"atomicNumber": 34, "symbol": "Se", "name": "Selenium", "atomicMass": 78.960, "group": 16, "period": 4, "category": "Nonmetal"},
      {"atomicNumber": 35, "symbol": "Br", "name": "Bromine", "atomicMass": 79.904, "group": 17, "period": 4, "category": "Halogen"},
      {"atomicNumber": 36, "symbol": "Kr", "name": "Krypton", "atomicMass": 83.798, "group": 18, "period": 4, "category": "Noble Gas"},
      {"atomicNumber": 37, "symbol": "Rb", "name": "Rubidium", "atomicMass": 85.468, "group": 1, "period": 5, "category": "Alkali Metal"},
      {"atomicNumber": 38, "symbol": "Sr", "name": "Strontium", "atomicMass": 87.620, "group": 2, "period": 5, "category": "Alkaline Earth Metal"},
      {"atomicNumber": 39, "symbol": "Y", "name": "Yttrium", "atomicMass": 88.906, "group": 3, "period": 5, "category": "Transition Metal"},
      {"atomicNumber": 40, "symbol": "Zr", "name": "Zirconium", "atomicMass": 91.224, "group": 4, "period": 5, "category": "Transition Metal"},
      {"atomicNumber": 41, "symbol": "Nb", "name": "Niobium", "atomicMass": 92.906, "group": 5, "period": 5, "category": "Transition Metal"},
      {"atomicNumber": 42, "symbol": "Mo", "name": "Molybdenum", "atomicMass": 95.960, "group": 6, "period": 5, "category": "Transition Metal"},
      {"atomicNumber": 43, "symbol": "Tc", "name": "Technetium", "atomicMass": 98, "group": 7, "period": 5, "category": "Transition Metal"},
      {"atomicNumber": 44, "symbol": "Ru", "name": "Ruthenium", "atomicMass": 101.070, "group": 8, "period": 5, "category": "Transition Metal"},
      {"atomicNumber": 45, "symbol": "Rh", "name": "Rhodium", "atomicMass": 102.906, "group": 9, "period": 5, "category": "Transition Metal"},
      {"atomicNumber": 46, "symbol": "Pd", "name": "Palladium", "atomicMass": 106.420, "group": 10, "period": 5, "category": "Transition Metal"},
      {"atomicNumber": 47, "symbol": "Ag", "name": "Silver", "atomicMass": 107.868, "group": 11, "period": 5, "category": "Transition Metal"},
      {"atomicNumber": 48, "symbol": "Cd", "name": "Cadmium", "atomicMass": 112.411, "group": 12, "period": 5, "category": "Transition Metal"},
      {"atomicNumber": 49, "symbol": "In", "name": "Indium", "atomicMass": 114.818, "group": 13, "period": 5, "category": "Post-transition Metal"},
      {"atomicNumber": 50, "symbol": "Sn", "name": "Tin", "atomicMass": 118.710, "group": 14, "period": 5, "category": "Post-transition Metal"},
      {"atomicNumber": 51, "symbol": "Sb", "name": "Antimony", "atomicMass": 121.760, "group": 15, "period": 5, "category": "Metalloid"},
      {"atomicNumber": 52, "symbol": "Te", "name": "Tellurium", "atomicMass": 127.600, "group": 16, "period": 5, "category": "Metalloid"},
      {"atomicNumber": 53, "symbol": "I", "name": "Iodine", "atomicMass": 126.904, "group": 17, "period": 5, "category": "Halogen"},
      {"atomicNumber": 54, "symbol": "Xe", "name": "Xenon", "atomicMass": 131.293, "group": 18, "period": 5, "category": "Noble Gas"},
      {"atomicNumber": 55, "symbol": "Cs", "name": "Cesium", "atomicMass": 132.905, "group": 1, "period": 6, "category": "Alkali Metal"},
      {"atomicNumber": 56, "symbol": "Ba", "name": "Barium", "atomicMass": 137.327, "group": 2, "period": 6, "category": "Alkaline Earth Metal"},
      {"atomicNumber": 57, "symbol": "La", "name": "Lanthanum", "atomicMass": 138.905, "group": null, "period": 6, "category": "Lanthanide"},
      {"atomicNumber": 58, "symbol": "Ce", "name": "Cerium", "atomicMass": 140.116, "group": null, "period": 6, "category": "Lanthanide"},
      {"atomicNumber": 59, "symbol": "Pr", "name": "Praseodymium", "atomicMass": 140.908, "group": null, "period": 6, "category": "Lanthanide"},
      {"atomicNumber": 60, "symbol": "Nd", "name": "Neodymium", "atomicMass": 144.242, "group": null, "period": 6, "category": "Lanthanide"},
      {"atomicNumber": 61, "symbol": "Pm", "name": "Promethium", "atomicMass": 145, "group": null, "period": 6, "category": "Lanthanide"},
      {"atomicNumber": 62, "symbol": "Sm", "name": "Samarium", "atomicMass": 150.360, "group": null, "period": 6, "category": "Lanthanide"},
      {"atomicNumber": 63, "symbol": "Eu", "name": "Europium", "atomicMass": 151.964, "group": null, "period": 6, "category": "Lanthanide"},
      {"atomicNumber": 64, "symbol": "Gd", "name": "Gadolinium", "atomicMass": 157.250, "group": null, "period": 6, "category": "Lanthanide"},
      {"atomicNumber": 65, "symbol": "Tb", "name": "Terbium", "atomicMass": 158.925, "group": null, "period": 6, "category": "Lanthanide"},
      {"atomicNumber": 66, "symbol": "Dy", "name": "Dysprosium", "atomicMass": 162.500, "group": null, "period": 6, "category": "Lanthanide"},
      {"atomicNumber": 67, "symbol": "Ho", "name": "Holmium", "atomicMass": 164.930, "group": null, "period": 6, "category": "Lanthanide"},
      {"atomicNumber": 68, "symbol": "Er", "name": "Erbium", "atomicMass": 167.259, "group": null, "period": 6, "category": "Lanthanide"},
      {"atomicNumber": 69, "symbol": "Tm", "name": "Thulium", "atomicMass": 168.934, "group": null, "period": 6, "category": "Lanthanide"},
      {"atomicNumber": 70, "symbol": "Yb", "name": "Ytterbium", "atomicMass": 173.045, "group": null, "period": 6, "category": "Lanthanide"},
      {"atomicNumber": 71, "symbol": "Lu", "name": "Lutetium", "atomicMass": 174.967, "group": 3, "period": 6, "category": "Lanthanide"},
      {"atomicNumber": 72, "symbol": "Hf", "name": "Hafnium", "atomicMass": 178.490, "group": 4, "period": 6, "category": "Transition Metal"},
      {"atomicNumber": 73, "symbol": "Ta", "name": "Tantalum", "atomicMass": 180.948, "group": 5, "period": 6, "category": "Transition Metal"},
      {"atomicNumber": 74, "symbol": "W", "name": "Tungsten", "atomicMass": 183.840, "group": 6, "period": 6, "category": "Transition Metal"},
      {"atomicNumber": 75, "symbol": "Re", "name": "Rhenium", "atomicMass": 186.207, "group": 7, "period": 6, "category": "Transition Metal"},
      {"atomicNumber": 76, "symbol": "Os", "name": "Osmium", "atomicMass": 190.230, "group": 8, "period": 6, "category": "Transition Metal"},
      {"atomicNumber": 77, "symbol": "Ir", "name": "Iridium", "atomicMass": 192.217, "group": 9, "period": 6, "category": "Transition Metal"},
      {"atomicNumber": 78, "symbol": "Pt", "name": "Platinum", "atomicMass": 195.084, "group": 10, "period": 6, "category": "Transition Metal"},
      {"atomicNumber": 79, "symbol": "Au", "name": "Gold", "atomicMass": 196.967, "group": 11, "period": 6, "category": "Transition Metal"},
      {"atomicNumber": 80, "symbol": "Hg", "name": "Mercury", "atomicMass": 200.592, "group": 12, "period": 6, "category": "Transition Metal"},
      {"atomicNumber": 81, "symbol": "Tl", "name": "Thallium", "atomicMass": 204.383, "group": 13, "period": 6, "category": "Post-transition Metal"},
      {"atomicNumber": 82, "symbol": "Pb", "name": "Lead", "atomicMass": 207.200, "group": 14, "period": 6, "category": "Post-transition Metal"},
      {"atomicNumber": 83, "symbol": "Bi", "name": "Bismuth", "atomicMass": 208.980, "group": 15, "period": 6, "category": "Post-transition Metal"},
      {"atomicNumber": 84, "symbol": "Po", "name": "Polonium", "atomicMass": 209, "group": 16, "period": 6, "category": "Post-transition Metal"},
      {"atomicNumber": 85, "symbol": "At", "name": "Astatine", "atomicMass": 210, "group": 17, "period": 6, "category": "Halogen"},
      {"atomicNumber": 86, "symbol": "Rn", "name": "Radon", "atomicMass": 222, "group": 18, "period": 6, "category": "Noble Gas"},
      {"atomicNumber": 87, "symbol": "Fr", "name": "Francium", "atomicMass": 223, "group": 1, "period": 7, "category": "Alkali Metal"},
      {"atomicNumber": 88, "symbol": "Ra", "name": "Radium", "atomicMass": 226, "group": 2, "period": 7, "category": "Alkaline Earth Metal"},
      {"atomicNumber": 89, "symbol": "Ac", "name": "Actinium", "atomicMass": 227, "group": null, "period": 7, "category": "Actinide"},
      {"atomicNumber": 90, "symbol": "Th", "name": "Thorium", "atomicMass": 232.038, "group": null, "period": 7, "category": "Actinide"},
      {"atomicNumber": 91, "symbol": "Pa", "name": "Protactinium", "atomicMass": 231.036, "group": null, "period": 7, "category": "Actinide"},
      {"atomicNumber": 92, "symbol": "U", "name": "Uranium", "atomicMass": 238.029, "group": null, "period": 7, "category": "Actinide"},
      {"atomicNumber": 93, "symbol": "Np", "name": "Neptunium", "atomicMass": 237, "group": null, "period": 7, "category": "Actinide"},
      {"atomicNumber": 94, "symbol": "Pu", "name": "Plutonium", "atomicMass": 244, "group": null, "period": 7, "category": "Actinide"},
      {"atomicNumber": 95, "symbol": "Am", "name": "Americium", "atomicMass": 243, "group": null, "period": 7, "category": "Actinide"},
      {"atomicNumber": 96, "symbol": "Cm", "name": "Curium", "atomicMass": 247, "group": null, "period": 7, "category": "Actinide"},
      {"atomicNumber": 97, "symbol": "Bk", "name": "Berkelium", "atomicMass": 247, "group": null, "period": 7, "category": "Actinide"},
      {"atomicNumber": 98, "symbol": "Cf", "name": "Californium", "atomicMass": 251, "group": null, "period": 7, "category": "Actinide"},
      {"atomicNumber": 99, "symbol": "Es", "name": "Einsteinium", "atomicMass": 252, "group": null, "period": 7, "category": "Actinide"},
      {"atomicNumber": 100, "symbol": "Fm", "name": "Fermium", "atomicMass": 257, "group": null, "period": 7, "category": "Actinide"},
      {"atomicNumber": 101, "symbol": "Md", "name": "Mendelevium", "atomicMass": 258, "group": null, "period": 7, "category": "Actinide"},
      {"atomicNumber": 102, "symbol": "No", "name": "Nobelium", "atomicMass": 259, "group": null, "period": 7, "category": "Actinide"},
      {"atomicNumber": 103, "symbol": "Lr", "name": "Lawrencium", "atomicMass": 262, "group": 3, "period": 7, "category": "Actinide"},
      {"atomicNumber": 104, "symbol": "Rf", "name": "Rutherfordium", "atomicMass": 267, "group": 4, "period": 7, "category": "Transition Metal"},
      {"atomicNumber": 105, "symbol": "Db", "name": "Dubnium", "atomicMass": 270, "group": 5, "period": 7, "category": "Transition Metal"},
      {"atomicNumber": 106, "symbol": "Sg", "name": "Seaborgium", "atomicMass": 271, "group": 6, "period": 7, "category": "Transition Metal"},
      {"atomicNumber": 107, "symbol": "Bh", "name": "Bohrium", "atomicMass": 272, "group": 7, "period": 7, "category": "Transition Metal"},
      {"atomicNumber": 108, "symbol": "Hs", "name": "Hassium", "atomicMass": 270, "group": 8, "period": 7, "category": "Transition Metal"},
      {"atomicNumber": 109, "symbol": "Mt", "name": "Meitnerium", "atomicMass": 276, "group": 9, "period": 7, "category": "Transition Metal"},
      {"atomicNumber": 110, "symbol": "Ds", "name": "Darmstadtium", "atomicMass": 281, "group": 10, "period": 7, "category": "Transition Metal"},
      {"atomicNumber": 111, "symbol": "Rg", "name": "Roentgenium", "atomicMass": 280, "group": 11, "period": 7, "category": "Transition Metal"},
      {"atomicNumber": 112, "symbol": "Cn", "name": "Copernicium", "atomicMass": 285, "group": 12, "period": 7, "category": "Transition Metal"},
      {"atomicNumber": 113, "symbol": "Nh", "name": "Nihonium", "atomicMass": 284, "group": 13, "period": 7, "category": "Post-transition Metal"},
      {"atomicNumber": 114, "symbol": "Fl", "name": "Flerovium", "atomicMass": 289, "group": 14, "period": 7, "category": "Post-transition Metal"},
      {"atomicNumber": 115, "symbol": "Mc", "name": "Moscovium", "atomicMass": 288, "group": 15, "period": 7, "category": "Post-transition Metal"},
      {"atomicNumber": 116, "symbol": "Lv", "name": "Livermorium", "atomicMass": 293, "group": 16, "period": 7, "category": "Post-transition Metal"},
      {"atomicNumber": 117, "symbol": "Ts", "name": "Tennessine", "atomicMass": 294, "group": 17, "period": 7, "category": "Halogen"},
      {"atomicNumber": 118, "symbol": "Og", "name": "Oganesson", "atomicMass": 294, "group": 18, "period": 7, "category": "Noble Gas"}
    ]
  }
  "categories": {
    "Alkali Metal": ["Group 1, except Hydrogen"],
    "Alkaline Earth Metal": ["Group 2"],
    "Transition Metal": ["Groups 3-12"],
    "Post-transition Metal": ["Groups 13-16, right side"],
    "Metalloid": ["Properties between metals and nonmetals"],
    "Nonmetal": ["Groups 14-18, top right"],
    "Halogen": ["Group 17"],
    "Noble Gas": ["Group 18"],
    "Lanthanide": ["Atomic numbers 57-71"],
    "Actinide": ["Atomic numbers 89-103"]
  }
  get elementLabels(): string[] {
    return this.periodicTable.elements.map((el: any) => el.name);
  }
}